### ISSUE TITLE
does not compile

### ISSUE THREAD

**Issue by arroyo** [andydotxyz/beebui#2]
When I run gen.sh I get

./gen.sh: line 9: /Users/jarroyo/.go/bin/fyne: No such file or directory

I added an empty file at that path using touch then ran gen.sh again.  It didn't give an error but the program was still 0 bytes.  

I also tried go build build and go install, but get a different error, "bundled.go:1:1: expected 'package', found 'EOF'"

What is the best way to compile the app?

**Comment by arroyo** [comment]
if I cd into the cmd/beebui folder and run go build it worked.  Go modules would make compiling this much easier.  fun app though!

**Comment by andydotxyz** [comment]
Thanks :)
Gen.sh is only used to rebuild the embedded data. The missing “fyne” file is referring to the command it uses to do the bundling (go get fyne.io/fyne/cmd/fyne), it’s not documented as it’s not intended to be used often sorry.

I’m not sure how modules would help - you’d still have to be in the binary folder to be able to compile?...
